#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

	mkdir -p "${AQQ_CACHE}"
	cd "${AQQ_CACHE}"
	{
		echo describe-snapshots describe-snapshots --owner self
		echo describe-images describe-images --owner self
		echo describe-instances describe-instances
		echo describe-volumes describe-volumes
		echo describe-subnets describe-subnets
		echo describe-vpcs describe-vpcs
		echo describe-network-interfaces describe-network-interfaces
		echo describe-security-groups describe-security-groups
		echo describe-dhcp-options describe-dhcp-options
		echo describe-iam-account-aliases list-account-aliases
		echo describe-iam-groups list-groups
		echo describe-iam-instance-profiles list-instance-profiles
		echo describe-iam-policies list-policies
		echo describe-iam-roles list-roles
		echo describe-iam-users list-users
		echo describe-iam-list-virtual-mfa-devices list-virtual-mfa-devices
	} | while read -r f l; do
				echo "$f $(echo "$l" | base64 -w 0)"
			done | runmany 4 2 'set -x; aq $(echo "$2" | base64 -d) > "${AQQ_CACHE}/$1"'
}

source sub "$BASH_SOURCE" "$@"
