#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  aqq '
    . as $idx 
      | $volume_status.VolumeStatuses 
      | map("\(.VolumeId) \(.VolumeStatus.Status) \($volumes[.VolumeId].Attachments[] | "\(.InstanceId) \(.Device) \($idx[.InstanceId].Tags.Name)")")' \
      | jq -r "$@"
}

source sub "$BASH_SOURCE" "$@"
