#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  aqq '. as $idx | $instance_status.InstanceStatuses | to_entries | map("\(.key) \(.value | "\(.InstanceState.Name) \(.InstanceStatus.Status) \(.SystemStatus.Status)") \($idx[.key].Tags.Name)")' | jq -r "$@"
}

source sub "$BASH_SOURCE" "$@"
