#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  aqq '. as $idx | map("\(.InstanceId) \(.BlockDeviceMappings[.RootDeviceName].Ebs.Volume.Encrypted) \($idx[.InstanceId].Tags.Name)")' | jq -r "$@"
}

source sub "$BASH_SOURCE" "$@"
